code --install-extension Cardinal90.multi-cursor-case-preserve
code --install-extension christian-kohler.npm-intellisense
code --install-extension ClemensPeters.format-json
code --install-extension clinyong.vscode-css-modules
code --install-extension dakshmiglani.hex-to-rgba
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.vscode-pull-request-github
code --install-extension heroboy.generate-switch-case-for-enum-type
code --install-extension MariusAlchimavicius.json-to-ts
code --install-extension oderwat.indent-rainbow
code --install-extension PKief.material-icon-theme
code --install-extension quicktype.quicktype
code --install-extension sburg.vscode-javascript-booster
code --install-extension statelyai.stately-vscode
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension wix.glean
code --install-extension wmaurer.change-case
